# Generated by Django 6.0 on 2025-12-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='especie',
            field=models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato')], default='Perro', max_length=20),
        ),
    ]
