# Generated by Django 6.0 on 2025-12-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_mascota_genero_alter_atencion_id_alter_cita_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='es_urgencia',
            field=models.BooleanField(default=False, verbose_name='Es Urgencia'),
        ),
    ]
