# Generated by Django 6.0 on 2025-12-07 20:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_cita_es_urgencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='fecha_registro',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
