# Generated by Django 6.0 on 2025-12-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_mascota_fecha_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='cancelado_por',
            field=models.CharField(blank=True, choices=[('CLIENTE', 'Cliente'), ('VETERINARIO', 'Veterinario'), ('SISTEMA', 'Sistema')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='fecha_cancelacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='motivo_cancelacion',
            field=models.TextField(blank=True),
        ),
    ]
