# Generated by Django 6.0 on 2025-12-08 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_cita_cancelado_por_cita_fecha_cancelacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listaespera',
            options={'ordering': ['numero_turno', 'fecha_solicitud'], 'verbose_name': 'Lista de Espera', 'verbose_name_plural': 'Listas de Espera'},
        ),
        migrations.AddField(
            model_name='listaespera',
            name='fecha_atencion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de inicio de atención', null=True),
        ),
        migrations.AddField(
            model_name='listaespera',
            name='mascota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lista_espera', to='clinic.mascota'),
        ),
        migrations.AddField(
            model_name='listaespera',
            name='motivo',
            field=models.TextField(blank=True, help_text='Motivo de la visita'),
        ),
        migrations.AddField(
            model_name='listaespera',
            name='numero_turno',
            field=models.IntegerField(blank=True, help_text='Número en la cola del día', null=True),
        ),
        migrations.AddField(
            model_name='listaespera',
            name='prioridad',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=10),
        ),
        migrations.AddField(
            model_name='listaespera',
            name='veterinario_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_espera', to='clinic.veterinario'),
        ),
        migrations.AlterField(
            model_name='listaespera',
            name='estado',
            field=models.CharField(choices=[('ESPERANDO', 'En Espera'), ('EN_ATENCION', 'En Atención'), ('ATENDIDO', 'Atendido'), ('CANCELADO', 'Cancelado'), ('PENDIENTE', 'Pendiente'), ('CONTACTADO', 'Contactado'), ('CERRADO', 'Cerrado')], default='ESPERANDO', max_length=20),
        ),
        migrations.AlterField(
            model_name='listaespera',
            name='preferencia',
            field=models.TextField(blank=True, help_text='Preferencia de horario o doctor'),
        ),
    ]
