# Generated by Django 6.0 on 2025-12-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_alter_listaespera_options_listaespera_fecha_atencion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='fecha_reagendamiento',
            field=models.DateTimeField(blank=True, help_text='Última vez que se reagendó', null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='motivo_reagendamiento',
            field=models.TextField(blank=True, help_text='Motivo del cambio de fecha/hora'),
        ),
    ]
